### ISSUE TITLE
install all

### ISSUE THREAD

**Issue by drlenux** [drlenux/runner-scripts#1]
`PHP Fatal error:  Uncaught Error: Call to undefined method scripts\Vagrant::reload() in /home/noname/project/php_scripts/run2/scripts/InstallAll.php:23
Stack trace:
#0 /home/noname/project/php_scripts/run2/scripts/Scripts.php(25): scripts\InstallAll->getListScripts()
#1 /home/noname/project/php_scripts/run2/app/Runner.php(83): scripts\Scripts->getList()
#2 /home/noname/project/php_scripts/run2/app/Runner.php(34): app\Runner->run('Commands list', Array)
#3 /home/noname/project/php_scripts/run2/app/App.php(90): app\Runner->__construct()
#4 /home/noname/project/php_scripts/run2/run(17): app\App->run()
#5 {main}
  thrown in /home/noname/project/php_scripts/run2/scripts/InstallAll.php on line 23
`

**Comment by drlenux** [comment]
completed
